apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: aashraf756/service-vault-passgenius:5vg3i9c4
          ports:
            - containerPort: 8080
