# authenticated-open-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authenticated-ingress  # You can rename this as needed
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/plugins: jwt-plugin
spec:
  ingressClassName: kong
  rules:
    - host: passgeniusapp.com
      http:
        paths:
          - path: /api/web
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user
                port:
                  number: 80
          - path: /api/email
            pathType: Prefix
            backend:
              service:
                name: email
                port:
                  number: 80
          - path: /api/vaults
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 80
