apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-ingress  # You can rename this as needed
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
    - host: 149.172.215.195

      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: authentication
                port:
                  number: 80

